#
# This is free software, lisence use MIT.
# 
# Copyright (C) 2019 P3TERX <https://p3terx.com>
# Copyright (C) 2020 KFERMercer <KFER.Mercer@gmail.com>
# 
# <https://github.com/KFERMercer/OpenWrt-CI>
#

name: Auto_build

on:
  push:
    branches: 
      - openwrt-19.07
  # schedule:
  #   - cron: 0 20 * * *
  release:
    types: [published]

jobs:

  build_openwrt:

    name: Build OpenWrt firmware

    runs-on: ubuntu-latest

    if: github.event.repository.owner.id == github.event.sender.id

    steps:

      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: openwrt-19.07

      - name: Space cleanup
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
            sudo rm -rf /swapfile /etc/apt/sources.list.d/* /usr/share/dotnet /usr/local/lib/android /opt/ghc
            sudo -E apt-get -qq update
            sudo -E apt-get -qq install build-essential asciidoc binutils bzip2 gawk gettext git libncurses5-dev libz-dev patch python3 unzip zlib1g-dev lib32gcc1 libc6-dev-i386 subversion flex uglifyjs git-core gcc-multilib p7zip p7zip-full msmtp libssl-dev texinfo libglib2.0-dev xmlto qemu-utils upx libelf-dev autoconf automake libtool autopoint device-tree-compiler g++-multilib antlr3 gperf
            sudo -E apt-get -qq autoremove --purge
            sudo -E apt-get -qq clean
            df -h

      - name: Update feeds
        run: |
              ./scripts/feeds update -a
              ./scripts/feeds install -a
              git clone --depth=1 https://github.com/jerrykuku/luci-theme-argon.git package/crackself/luci-theme-argon
              #git clone --depth=1 https://github.com/kenzok8/openwrt-packages.git package/crackself/openwrt-packages
              git clone --depth=1 https://github.com/tty228/luci-app-serverchan.git  package/crackself/luci-app-serverchan
              git clone --depth=1 https://github.com/jerrykuku/luci-app-jd-dailybonus.git package/crackself/luci-app-jd-dailybonus
              git clone --depth=1 -b master https://github.com/vernesong/OpenClash.git package/crackself//OpenClash

      - name: Generate configuration file
        run: |
          rm -f ./.config*
          touch ./.config

          #
          # 在 cat >> .config <<EOF 到 EOF 之间粘贴你的编译配置, 需注意缩进关系
          # 例如:

        cat >> .config <<EOF
        # CONFIG_PACKAGE_luci-app-adblock is not set
        CONFIG_PACKAGE_luci-app-adbyby-plus=y
        CONFIG_PACKAGE_luci-app-adguardhome=y
        # CONFIG_PACKAGE_luci-app-advanced-reboot is not set
        # CONFIG_PACKAGE_luci-app-ahcp is not set
        # CONFIG_PACKAGE_luci-app-amule is not set
        # CONFIG_PACKAGE_luci-app-aria2 is not set
        # CONFIG_PACKAGE_luci-app-arpbind is not set
        # CONFIG_PACKAGE_luci-app-attendedsysupgrade is not set
        CONFIG_PACKAGE_luci-app-autoreboot=y
        # CONFIG_PACKAGE_luci-app-baidupcs-web is not set
        # CONFIG_PACKAGE_luci-app-bcp38 is not set
        # CONFIG_PACKAGE_luci-app-bird1-ipv4 is not set
        # CONFIG_PACKAGE_luci-app-bird1-ipv6 is not set
        # CONFIG_PACKAGE_luci-app-bmx6 is not set
        # CONFIG_PACKAGE_luci-app-brook-server is not set
        CONFIG_PACKAGE_luci-app-cifs-mount=y
        # CONFIG_PACKAGE_luci-app-cjdns is not set
        # CONFIG_PACKAGE_luci-app-clamav is not set
        # CONFIG_PACKAGE_luci-app-commands is not set
        CONFIG_PACKAGE_luci-app-control-timewol=y
        CONFIG_PACKAGE_luci-app-control-webrestriction=y
        CONFIG_PACKAGE_luci-app-control-weburl=y
        # CONFIG_PACKAGE_luci-app-cshark is not set
        CONFIG_PACKAGE_luci-app-ddns=y
        # CONFIG_PACKAGE_luci-app-diag-core is not set
        CONFIG_PACKAGE_luci-app-diskman=y
        CONFIG_PACKAGE_luci-app-diskman_INCLUDE_btrfs_progs=y
        CONFIG_PACKAGE_luci-app-diskman_INCLUDE_lsblk=y
        # CONFIG_PACKAGE_luci-app-diskman_INCLUDE_mdadm is not set
        # CONFIG_PACKAGE_luci-app-dnscrypt-proxy is not set
        # CONFIG_PACKAGE_luci-app-dnsforwarder is not set
        # CONFIG_PACKAGE_luci-app-dockerman is not set
        # CONFIG_PACKAGE_luci-app-dockerman_INCLUDE_docker_ce is not set
        CONFIG_PACKAGE_luci-app-dockerman_INCLUDE_ttyd=y
        # CONFIG_PACKAGE_luci-app-dump1090 is not set
        # CONFIG_PACKAGE_luci-app-dynapoint is not set
        # CONFIG_PACKAGE_luci-app-e2guardian is not set
        CONFIG_PACKAGE_luci-app-fileassistant=y
        CONFIG_PACKAGE_luci-app-filebrowser=y
        CONFIG_PACKAGE_luci-app-filetransfer=y
        CONFIG_PACKAGE_luci-app-firewall=y
        # CONFIG_PACKAGE_luci-app-flowoffload is not set
        # CONFIG_PACKAGE_luci-app-freifunk-diagnostics is not set
        # CONFIG_PACKAGE_luci-app-freifunk-policyrouting is not set
        # CONFIG_PACKAGE_luci-app-freifunk-widgets is not set
        CONFIG_PACKAGE_luci-app-frpc=y
        CONFIG_PACKAGE_luci-app-frps=y
        # CONFIG_PACKAGE_luci-app-fwknopd is not set
        # CONFIG_PACKAGE_luci-app-guest-wifi is not set
        CONFIG_PACKAGE_luci-app-hd-idle=y
        # CONFIG_PACKAGE_luci-app-hnet is not set
        # CONFIG_PACKAGE_luci-app-https-dns-proxy is not set
        CONFIG_PACKAGE_luci-app-ipsec-vpnserver-manyusers=y
        CONFIG_PACKAGE_luci-app-jd-dailybonus=y
        CONFIG_PACKAGE_luci-app-kcptun=y
        CONFIG_PACKAGE_luci-app-kodexplorer=y
        # CONFIG_PACKAGE_luci-app-ksmbd is not set
        # CONFIG_PACKAGE_luci-app-lxc is not set
        # CONFIG_PACKAGE_luci-app-meshwizard is not set
        # CONFIG_PACKAGE_luci-app-minidlna is not set
        # CONFIG_PACKAGE_luci-app-mjpg-streamer is not set
        # CONFIG_PACKAGE_luci-app-mtwifi is not set
        CONFIG_PACKAGE_luci-app-mwan3=y
        CONFIG_PACKAGE_luci-app-mwan3helper=y
        CONFIG_PACKAGE_luci-app-netdata=y
        CONFIG_PACKAGE_luci-app-nfs=y
        CONFIG_PACKAGE_luci-app-nginx-pingos=y
        # CONFIG_PACKAGE_luci-app-nlbwmon is not set
        # CONFIG_PACKAGE_luci-app-noddos is not set
        CONFIG_PACKAGE_luci-app-nps=y
        # CONFIG_PACKAGE_luci-app-ntpc is not set
        # CONFIG_PACKAGE_luci-app-oaf is not set
        # CONFIG_PACKAGE_luci-app-ocserv is not set
        # CONFIG_PACKAGE_luci-app-olsr is not set
        # CONFIG_PACKAGE_luci-app-olsr-services is not set
        # CONFIG_PACKAGE_luci-app-olsr-viz is not set
        # CONFIG_PACKAGE_luci-app-openvpn is not set
        # CONFIG_PACKAGE_luci-app-openvpn-server is not set
        # CONFIG_PACKAGE_luci-app-p910nd is not set
        # CONFIG_PACKAGE_luci-app-pagekitec is not set
        CONFIG_PACKAGE_luci-app-passwall=y


        #
        # Configuration
        #
        CONFIG_PACKAGE_luci-app-passwall_INCLUDE_ipt2socks=y
        CONFIG_PACKAGE_luci-app-passwall_INCLUDE_Shadowsocks=y
        CONFIG_PACKAGE_luci-app-passwall_INCLUDE_ShadowsocksR=y
        CONFIG_PACKAGE_luci-app-passwall_INCLUDE_ShadowsocksR_Server=y
        CONFIG_PACKAGE_luci-app-passwall_INCLUDE_V2ray=y
        CONFIG_PACKAGE_luci-app-passwall_INCLUDE_Trojan_Plus=y
        CONFIG_PACKAGE_luci-app-passwall_INCLUDE_Trojan_GO=y
        CONFIG_PACKAGE_luci-app-passwall_INCLUDE_Brook=y
        CONFIG_PACKAGE_luci-app-passwall_INCLUDE_kcptun=y
        CONFIG_PACKAGE_luci-app-passwall_INCLUDE_haproxy=y
        CONFIG_PACKAGE_luci-app-passwall_INCLUDE_ChinaDNS_NG=y
        CONFIG_PACKAGE_luci-app-passwall_INCLUDE_pdnsd=y
        CONFIG_PACKAGE_luci-app-passwall_INCLUDE_https_dns_proxy=y
        CONFIG_PACKAGE_luci-app-passwall_INCLUDE_dns2socks=y
        CONFIG_PACKAGE_luci-app-passwall_INCLUDE_v2ray-plugin=y
        CONFIG_PACKAGE_luci-app-passwall_INCLUDE_simple-obfs=y
        # end of Configuration

        # CONFIG_PACKAGE_luci-app-polipo is not set
        CONFIG_PACKAGE_luci-app-pppoe-relay=y
        CONFIG_PACKAGE_luci-app-pppoe-server=y
        CONFIG_PACKAGE_luci-app-pptp-vpnserver-manyusers=y
        # CONFIG_PACKAGE_luci-app-privoxy is not set
        # CONFIG_PACKAGE_luci-app-qbittorrent is not set
        # CONFIG_PACKAGE_luci-app-qos is not set
        # CONFIG_PACKAGE_luci-app-radicale is not set
        CONFIG_PACKAGE_luci-app-ramfree=y
        # CONFIG_PACKAGE_luci-app-rp-pppoe-server is not set
        CONFIG_PACKAGE_luci-app-samba=y
        # CONFIG_PACKAGE_luci-app-samba4 is not set
        CONFIG_PACKAGE_luci-app-sfe=y
        # CONFIG_PACKAGE_luci-app-shadowsocks-libev is not set
        # CONFIG_PACKAGE_luci-app-shairplay is not set
        # CONFIG_PACKAGE_luci-app-siitwizard is not set
        # CONFIG_PACKAGE_luci-app-simple-adblock is not set
        CONFIG_PACKAGE_luci-app-smartdns=y
        CONFIG_PACKAGE_luci-app-softethervpn=y
        # CONFIG_PACKAGE_luci-app-splash is not set
        # CONFIG_PACKAGE_luci-app-sqm is not set
        # CONFIG_PACKAGE_luci-app-squid is not set
        # CONFIG_PACKAGE_luci-app-ssr-libev-server is not set
        CONFIG_PACKAGE_luci-app-ssr-mudb-server=y
        # CONFIG_PACKAGE_luci-app-statistics is not set
        CONFIG_PACKAGE_luci-app-syncdial=y
        # CONFIG_PACKAGE_luci-app-syncthing is not set
        CONFIG_PACKAGE_luci-app-tcpdump=y
        CONFIG_PACKAGE_luci-app-timecontrol=y
        # CONFIG_PACKAGE_luci-app-tinyproxy is not set
        # CONFIG_PACKAGE_luci-app-transmission is not set
        # CONFIG_PACKAGE_luci-app-travelmate is not set
        # CONFIG_PACKAGE_luci-app-trojan-server is not set
        CONFIG_PACKAGE_luci-app-ttyd=y
        # CONFIG_PACKAGE_luci-app-udpxy is not set
        # CONFIG_PACKAGE_luci-app-uhttpd is not set
        CONFIG_PACKAGE_luci-app-unblockmusic=y
        CONFIG_UnblockNeteaseMusic_Go=y
        # CONFIG_UnblockNeteaseMusic_NodeJS is not set
        # CONFIG_PACKAGE_luci-app-unbound is not set
        CONFIG_PACKAGE_luci-app-upnp=y
        CONFIG_PACKAGE_luci-app-usb-printer=y
        # CONFIG_PACKAGE_luci-app-v2ray-server is not set
        # CONFIG_PACKAGE_luci-app-verysync is not set
        CONFIG_PACKAGE_luci-app-vlmcsd=y
        # CONFIG_PACKAGE_luci-app-vnstat is not set
        # CONFIG_PACKAGE_luci-app-vpnbypass is not set
        CONFIG_PACKAGE_luci-app-vsftpd=y
        # CONFIG_PACKAGE_luci-app-watchcat is not set
        # CONFIG_PACKAGE_luci-app-webadmin is not set
        # CONFIG_PACKAGE_luci-app-wifischedule is not set
        # CONFIG_PACKAGE_luci-app-wireguard is not set
        CONFIG_PACKAGE_luci-app-wol=y
        # CONFIG_PACKAGE_luci-app-wrtbwmon is not set
        # CONFIG_PACKAGE_luci-app-xlnetacc is not set
        CONFIG_PACKAGE_luci-app-zerotier=y
        CONFIG_PACKAGE_luci-app-serverchan=y


        # 主题
        CONFIG_PACKAGE_luci-theme-argon-jerrykuku=y
        CONFIG_PACKAGE_luci-theme-bootstrap=y

        # 协议
        CONFIG_PACKAGE_luci-proto-3g=y
        CONFIG_PACKAGE_luci-proto-bonding=y
        CONFIG_PACKAGE_luci-proto-ipip=y
        CONFIG_PACKAGE_luci-proto-ipv6=y
        CONFIG_PACKAGE_luci-proto-openconnect=y
        CONFIG_PACKAGE_luci-proto-ppp=y
        CONFIG_PACKAGE_luci-proto-qmi=y
        CONFIG_PACKAGE_luci-proto-relay=y
        CONFIG_PACKAGE_luci-proto-vpnc=y
        CONFIG_PACKAGE_luci-proto-wireguard=y
        EOF

          #
          # ===============================================================
          # 

          sed -i 's/^[ \t]*//g' ./.config
          make defconfig

      - name: Make download
        run: |
          make download -j8 || make download -j1 V=s
          rm -rf $(find ./dl/ -size -1024c)
          df -h

      - name: Compile firmware
        run: |
          make -j$(nproc) || make -j1 V=s
          echo "======================="
          echo "Space usage:"
          echo "======================="
          df -h
          echo "======================="
          du -h ./ --max-depth=1
          du -h /mnt/openwrt/ --max-depth=1 || true

      - name: Prepare artifact
        run: |
          mkdir -p ./artifact/firmware
          mkdir -p ./artifact/package
          mkdir -p ./artifact/buildinfo
          rm -rf $(find ./bin/targets/ -type d -name "packages")
          cp -rf $(find ./bin/targets/ -type f) ./artifact/firmware/
          cp -rf $(find ./bin/packages/ -type f -name "*.ipk") ./artifact/package/
          cp -rf $(find ./bin/targets/ -type f -name "*.buildinfo" -o -name "*.manifest") ./artifact/buildinfo/

      - name: Deliver buildinfo
        uses: actions/upload-artifact@v2
        with:
          name: OpenWrt_buildinfo
          path: ./artifact/buildinfo/

      - name: Deliver package
        uses: actions/upload-artifact@v2
        with:
          name: OpenWrt_package
          path: ./artifact/package/

      - name: Deliver firmware
        uses: actions/upload-artifact@v2
        with:
          name: OpenWrt_firmware
          path: ./bin/targets/

      - name: Upload release asset
        if: github.event == 'release'
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.RELEASE }}
          file: ./artifact/firmware/*
          tag: ${{ github.ref }}
          file_glob: true
